### ISSUE TITLE
Code block cannot use custom params  when upgraded to V4 in MDX

### ISSUE THREAD

**Issue by imjeen** [hashicorp/next-mdx-remote#294]
when using `  "next-mdx-remote": "^3.0.8"`, I can add extra params to highlight lines in MDX like below.
<pre>
```css highlight=[[4,7]]
.scale-hover {
  position: relative;
}
.scale-hover::after {
  background-color: pink;
  content: "";
}
```
</pre>

 Upgraded to `4.1.0`,  the code block is missing extra params.

And how I use the custom params for code block in MDX?
